/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacypolicyRouteImport } from './routes/privacypolicy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PQ7kf9m2dxzRouteImport } from './routes/p.q7kf9m2dxz'

const PrivacypolicyRoute = PrivacypolicyRouteImport.update({
  id: '/privacypolicy',
  path: '/privacypolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PQ7kf9m2dxzRoute = PQ7kf9m2dxzRouteImport.update({
  id: '/p/q7kf9m2dxz',
  path: '/p/q7kf9m2dxz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/p/q7kf9m2dxz': typeof PQ7kf9m2dxzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/p/q7kf9m2dxz': typeof PQ7kf9m2dxzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/p/q7kf9m2dxz': typeof PQ7kf9m2dxzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/privacypolicy' | '/p/q7kf9m2dxz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/privacypolicy' | '/p/q7kf9m2dxz'
  id: '__root__' | '/' | '/about' | '/privacypolicy' | '/p/q7kf9m2dxz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacypolicyRoute: typeof PrivacypolicyRoute
  PQ7kf9m2dxzRoute: typeof PQ7kf9m2dxzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacypolicy': {
      id: '/privacypolicy'
      path: '/privacypolicy'
      fullPath: '/privacypolicy'
      preLoaderRoute: typeof PrivacypolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/q7kf9m2dxz': {
      id: '/p/q7kf9m2dxz'
      path: '/p/q7kf9m2dxz'
      fullPath: '/p/q7kf9m2dxz'
      preLoaderRoute: typeof PQ7kf9m2dxzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacypolicyRoute: PrivacypolicyRoute,
  PQ7kf9m2dxzRoute: PQ7kf9m2dxzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
