/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VcardRouteImport } from './routes/vcard'
import { Route as PrivacypolicyRouteImport } from './routes/privacypolicy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VcardRoute = VcardRouteImport.update({
  id: '/vcard',
  path: '/vcard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacypolicyRoute = PrivacypolicyRouteImport.update({
  id: '/privacypolicy',
  path: '/privacypolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/vcard': typeof VcardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/vcard': typeof VcardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/vcard': typeof VcardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/privacypolicy' | '/vcard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/privacypolicy' | '/vcard'
  id: '__root__' | '/' | '/about' | '/privacypolicy' | '/vcard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacypolicyRoute: typeof PrivacypolicyRoute
  VcardRoute: typeof VcardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vcard': {
      id: '/vcard'
      path: '/vcard'
      fullPath: '/vcard'
      preLoaderRoute: typeof VcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacypolicy': {
      id: '/privacypolicy'
      path: '/privacypolicy'
      fullPath: '/privacypolicy'
      preLoaderRoute: typeof PrivacypolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacypolicyRoute: PrivacypolicyRoute,
  VcardRoute: VcardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
